language: node_js
cache: yarn
node_js:
  - node
branches:
  only:
    - master
script:
  - yarn run test
  - yarn run build:example
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
