language: node_js
cache: yarn
node_js:
  - node
script:
  - yarn run build:example
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
